Update to support pubKeyHash and scriptHash for zcash forks
BitGo/ecpair pull request #26
Opened 2024-05-16 14:54 UTC by stultusmundi

Description
When creating Zcash ECPAIR from WIF and passing network options, a typeforce check will fail.

Reason
Because Zcash and some forks based on it have pubKeyHash and scriptHash bigger than UInt8

These two values don't appear to be used in this library.

2024-05-24 13:50 UTC, OttoAllmendinger requested changes
Ideally this would be a separate type just for Zcash ECPairs. For all other coins UInt8 is still the correct type.

2024-10-31 09:17 UTC, OttoAllmendinger commented on package.json
> +  "name": "@runonflux/bitgo-ecpair",
did you push to the wrong remote by any chance?

2024-10-31 09:18 UTC, OttoAllmendinger commented
sorry, this change is not useful for the BitGo stack

2024-10-31 09:18 UTC, closed without merging

2024-10-31 14:45 UTC, stultusmundi commented
Yes sorry about this. I made a mistake.